language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=abcl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  - sudo apt-get update

script:
  - cl -e '(ql:quickload :birch.test)'
       -e '(setf *debugger-hook*
                 (lambda (cl-user::c cl-user::h)
                   (declare (ignore cl-user::c cl-user::h))
                   (uiop:quit -1)))'
       -e '(asdf:test-system :birch)'
